#!/bin/bash
TMP_PATH="tmp"
DATA_PATH="data/dubna1"
TEST_EXT=".test13"
RUN_EXT=".5"
EXT="$TEST_EXT$RUN_EXT"

N=80

if [ ! -d $TMP_PATH ]
then
	mkdir $TMP_PATH
fi

cd interpolation
echo $N | ./calculateOmega \
../$DATA_PATH/dubna1_samples \
../$DATA_PATH/dubna1_h \
../$DATA_PATH/dubna1_r \
prop_om$TEST_EXT \
> ../$TMP_PATH/omega$EXT \
&& cd ../$TMP_PATH \
&& rm *$EXT 

echo "$EXT finished!"
