/*
 * Copyright (c) 2002, 2017 Jens Keiner, Stefan Kunis, Daniel Potts
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/* Generated by tests/sincgen -- do not edit.
 *
 * Coefficients for log|sinc(x)|, one set per floating-point format.
 * Regenerate with
 *
 *   uv run --with mpmath==1.3.0 python -m tests.sincgen.generate
 *
 * Two ranges per format, split at NFFT_LOG_SINC_SPLIT:
 *
 *   |x| <= split   log|sinc(x)| = y * Q(y),  y = x*x, Horner in y.
 *                  The leading y makes the form exact at x = 0, and the
 *                  coefficients follow the Taylor series of log sinc
 *                  (-1/6, -1/180, -1/2835, ...), all negative, so the sum
 *                  cannot cancel.
 *
 *   |x| >  split   log|sinc(x)| = LOG(FABS(SIN(x)/x)), no coefficients.
 *
 * Q is a weighted minimax fit, the weight chosen so the relative error of
 * y*Q(y) equioscillates. What callers need is the absolute error of the
 * result, since they form EXP(2m * log_sinc(x)); branch 1 gives |L|*eps where
 * the direct logarithm could only give eps.
 */

#ifndef NFFT_SINC_DATA_H
#define NFFT_SINC_DATA_H

#if MANT_DIG == 24
  /* IEEE 754 single precision, 32 bits. */
#  define NFFT_LOG_SINC_SPLIT K(2.0)
  static const R NFFT_LOG_SINC_Q[] =
  {
      K(-1.66666666644e-1),
      K(-5.55555665315e-3),
      K(-3.52724913338e-4),
      K(-2.64820817680e-5),
      K(-2.09573588537e-6),
      K(-2.17455911075e-7),
      K(3.88846903322e-9),
      K(-7.56441719121e-9),
      K(9.81059419749e-10),
      K(-1.04188012233e-10),
  };

#elif MANT_DIG == 64
  /* Intel double extended, 80 bits. */
#  define NFFT_LOG_SINC_SPLIT K(2.0)
  static const R NFFT_LOG_SINC_Q[] =
  {
      K(-1.666666666666666666666953e-1),
      K(-5.555555555555555548077426e-3),
      K(-3.527336860670197249993535e-4),
      K(-2.645502645502085343269809e-5),
      K(-2.137779915608935253944031e-6),
      K(-1.803670231130820379335829e-7),
      K(-1.566139240163228281174242e-8),
      K(-1.388410180740436044040734e-9),
      K(-1.250492139495031919080634e-10),
      K(-1.139422030699562227336875e-11),
      K(-1.059902453986397930597604e-12),
      K(-8.886858041530835942033467e-14),
      K(-1.534164561370312691687357e-14),
      K(2.695149408659355504480426e-15),
      K(-1.704469754460829392895540e-15),
      K(5.839272617915575655146929e-16),
      K(-1.716823330153973862199595e-16),
      K(3.861747690587405505054640e-17),
      K(-6.728329548369730816650672e-18),
      K(8.669471848065446780340573e-19),
      K(-7.874453856297094969954481e-20),
      K(4.499691186200444741951703e-21),
      K(-1.251824897149332374936106e-22),
  };

#elif MANT_DIG == 113
  /* IEEE 754 quadruple precision, 128 bits. */
#  define NFFT_LOG_SINC_SPLIT K(2.0)
  static const R NFFT_LOG_SINC_Q[] =
  {
      K(-1.666666666666666666666666666666666666537e-1),
      K(-5.555555555555555555555555555555565876946e-3),
      K(-3.527336860670194003527336860656546320164e-4),
      K(-2.645502645502645502645502652706021727150e-5),
      K(-2.137779915557693335471111218942242343974e-6),
      K(-1.803670234005331007095029811372229711320e-7),
      K(-1.566139132276698414222643987367565404559e-8),
      K(-1.388413049373729945822752050291795900765e-9),
      K(-1.250435917600499374500039456305439994621e-10),
      K(-1.140257560229620502822976425326140651046e-11),
      K(-1.050292390863306136657964494465073427916e-12),
      K(-9.754877841738105758011852634446306769289e-14),
      K(-9.123468227032776638605103562258286396411e-15),
      K(-8.583719846609481606943021513827043549413e-16),
      K(-8.117316425845120477141195140209282225113e-17),
      K(-7.710552744089478975492004072114367365626e-18),
      K(-7.352500015646032744451575382609286721101e-19),
      K(-7.040172665628329346353723005100088855764e-20),
      K(-6.712142399089599852741011338104674512082e-21),
      K(-6.873128935559107935283456164207649446534e-22),
      K(-3.369653631968304126566542983201409583541e-23),
      K(-2.591235655362151274036056813747940924643e-23),
      K(1.131654597199894557338380767482514116982e-23),
      K(-6.330584767836800323674474061631341717418e-24),
      K(2.899469152769243515004139000360344560715e-24),
      K(-1.181987379074496993131659800549545265189e-24),
      K(4.213873479468846214008429886191885648726e-25),
      K(-1.315774142388511988344930071205250414761e-25),
      K(3.583460082048415170134299040450130181161e-26),
      K(-8.477354327647212528027817553975392325531e-27),
      K(1.731655688754826103170580796110116458821e-27),
      K(-3.030859563326476185876558872917412892275e-28),
      K(4.499234783568802504663861879510199169832e-29),
      K(-5.588439772357389024811679845943325614894e-30),
      K(5.701635713824132716478544593034521787698e-31),
      K(-4.655664179468163731633063667307446181950e-32),
      K(2.927481308565499967532077016420559165285e-33),
      K(-1.332269598622514129750080413083213632125e-34),
      K(3.911776157025872746878602445346864764805e-36),
      K(-5.580058455742725863350611282226215117795e-38),
  };

#else
  /* IEEE 754 double precision, 64 bits. Also the fallback for any format not named above.
   * Correct there only if that format is no wider than double. */
#  define NFFT_LOG_SINC_SPLIT K(2.0)
  static const R NFFT_LOG_SINC_Q[] =
  {
      K(-1.6666666666666666665e-1),
      K(-5.5555555555555585504e-3),
      K(-3.5273368606692134924e-4),
      K(-2.6455026456299630084e-5),
      K(-2.1377799068234839435e-6),
      K(-1.8036705996251151081e-7),
      K(-1.5661289595572996190e-8),
      K(-1.3886118783729202390e-9),
      K(-1.2476016771488067581e-10),
      K(-1.1704910397092082486e-11),
      K(-8.0474392366909467288e-13),
      K(-2.5100112097143963671e-13),
      K(6.5011136427223707191e-14),
      K(-2.8512176494806345975e-14),
      K(7.8212205243521842979e-15),
      K(-1.7092596406887604834e-15),
      K(2.6727239538307191438e-16),
      K(-2.9364452431798914301e-17),
      K(1.9979100994065501054e-18),
      K(-6.6847254593947211013e-20),
  };
#endif

#endif /* NFFT_SINC_DATA_H */

