/*
 * Copyright (c) 2026 Jens Keiner, Stefan Kunis, Daniel Potts
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/* Data-driven acceptance tests for the coreless native NDFT solvers
 * (kernel/nfft/ndft-1d.c, ndft-nd.c) against the reference data generated by
 * tests/refgen: each case file is read, the native path forced with
 * NFFT_NO_FAST_NATIVE, and the computed output compared with the file's. */

#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <CUnit/CUnit.h>
#include "config.h"
#include "nfft3.h"
#include "infft.h"
#include "iplanner.h"
#include "nplan.h"

#include "data/generated/nfft_native_testcases.h"

/* Read one whitespace-delimited case file: d, N[d], M, x[M*d], f_hat[NN] as
 * "re im" pairs, f[M] as "re im" pairs. The token format is produced by
 * tests/refgen/io_format.py. */
static int read_case(const char *rel, int *d, INT **N, INT *NN, INT *M, R **x,
                     C **f_hat, C **f) {
  char path[4096];
  FILE *fp;
  int t;
  INT j, nn = 1;
  *N = NULL;
  *x = NULL;
  *f_hat = NULL;
  *f = NULL;
  snprintf(path, sizeof path, "%s/tests/%s", ABS_SRCDIR, rel);
  fp = fopen(path, "r");
  if (!fp)
    return 0;
  if (fscanf(fp, "%d", d) != 1) {
    fclose(fp);
    return 0;
  }
  *N = (INT *)Y(malloc)((size_t)*d * sizeof(INT));
  for (t = 0; t < *d; t++) {
    long v;
    if (fscanf(fp, "%ld", &v) != 1) {
      fclose(fp);
      Y(free)
      (*N);
      *N = NULL;
      return 0;
    }
    (*N)[t] = (INT)v;
    nn *= (INT)v;
  }
  {
    long v;
    if (fscanf(fp, "%ld", &v) != 1) {
      fclose(fp);
      Y(free)
      (*N);
      *N = NULL;
      return 0;
    }
    *M = (INT)v;
  }
  *NN = nn;
  *x = (R *)Y(malloc)((size_t)(*d * *M) * sizeof(R));
  for (j = 0; j < *d * *M; j++) {
    double v;
    if (fscanf(fp, "%lf", &v) != 1) {
      fclose(fp);
      Y(free)
      (*N);
      *N = NULL;
      Y(free)
      (*x);
      *x = NULL;
      return 0;
    }
    (*x)[j] = (R)v;
  }
  *f_hat = (C *)Y(malloc)((size_t)nn * sizeof(C));
  for (j = 0; j < nn; j++) {
    double re, im;
    if (fscanf(fp, "%lf %lf", &re, &im) != 2) {
      fclose(fp);
      Y(free)
      (*N);
      *N = NULL;
      Y(free)
      (*x);
      *x = NULL;
      Y(free)
      (*f_hat);
      *f_hat = NULL;
      return 0;
    }
    (*f_hat)[j] = (R)re + II * (R)im;
  }
  *f = (C *)Y(malloc)((size_t)*M * sizeof(C));
  for (j = 0; j < *M; j++) {
    double re, im;
    if (fscanf(fp, "%lf %lf", &re, &im) != 2) {
      fclose(fp);
      Y(free)
      (*N);
      *N = NULL;
      Y(free)
      (*x);
      *x = NULL;
      Y(free)
      (*f_hat);
      *f_hat = NULL;
      Y(free)
      (*f);
      *f = NULL;
      return 0;
    }
    (*f)[j] = (R)re + II * (R)im;
  }
  fclose(fp);
  return 1;
}

static R rel_max_errC(const C *a, const C *b, INT len) {
  R num = (R)0, den = (R)0;
  INT j;
  for (j = 0; j < len; j++) {
    R e = CABS(a[j] - b[j]);
    if (e > num)
      num = e;
    if (CABS(b[j]) > den)
      den = CABS(b[j]);
  }
  return den > (R)0 ? num / den : num;
}

/* Drive one testcase (forward or adjoint, per tc->kind) against the native
 * solver, forced via NFFT_NO_FAST_NATIVE | steer. */
static void run_native(const native_testcase_t *tc, unsigned steer) {
  int d, t;
  INT *N, NN, M, *n;
  R *x;
  C *f_hat, *f;
  Y(plan_ng) * p;
  R tol = (R)1.0e-9;
  if ((R)1.0e5 * EPSILON > tol)
    tol = (R)1.0e5 * EPSILON;
  if (!read_case(tc->filename, &d, &N, &NN, &M, &x, &f_hat, &f)) {
    CU_FAIL("read_case failed");
    Y(free)
    (N);
    Y(free)
    (x);
    Y(free)
    (f_hat);
    Y(free)
    (f);
    return;
  }
  n = (INT *)Y(malloc)((size_t)d * sizeof(INT));
  for (t = 0; t < d; t++)
    n[t] = 2 * N[t] < 2 ? 2 : 2 * N[t]; /* any n >= N; direct native ignores it */

  if (tc->kind == 0) /* trafo: input f_hat, expected f */
  {
    C *save_fhat = (C *)Y(malloc)((size_t)NN * sizeof(C));
    C *got = (C *)Y(malloc)((size_t)M * sizeof(C));
    INT j;
    for (j = 0; j < NN; j++)
      save_fhat[j] = f_hat[j];
    p = Y(plan_ng_guru)(d, N, tc->variant, n, M, 6, NFFT_WINDOW_KAISER_BESSEL,
                        x, f_hat, got, 0u,
                        NFFT_ESTIMATE | NFFT_NO_FAST_NATIVE | steer);
    CU_ASSERT_PTR_NOT_NULL_FATAL(p);
    Y(precompute)
    (p);
    for (j = 0; j < NN; j++)
      f_hat[j] = save_fhat[j];
    Y(execute)
    (p);
    CU_ASSERT(rel_max_errC(got, f, M) < tol);
    Y(plan_ng_destroy)
    (p);
    Y(free)
    (save_fhat);
    Y(free)
    (got);
  } else /* adjoint: input f, expected f_hat */
  {
    C *save_f = (C *)Y(malloc)((size_t)M * sizeof(C));
    C *got = (C *)Y(malloc)((size_t)NN * sizeof(C));
    INT j;
    for (j = 0; j < M; j++)
      save_f[j] = f[j];
    p = Y(plan_ng_guru)(d, N, tc->variant, n, M, 6, NFFT_WINDOW_KAISER_BESSEL,
                        x, got, f, 0u,
                        NFFT_ESTIMATE | NFFT_NO_FAST_NATIVE | steer);
    CU_ASSERT_PTR_NOT_NULL_FATAL(p);
    Y(precompute)
    (p);
    for (j = 0; j < M; j++)
      f[j] = save_f[j];
    Y(execute_adjoint)
    (p);
    CU_ASSERT(rel_max_errC(got, f_hat, NN) < tol);
    Y(plan_ng_destroy)
    (p);
    Y(free)
    (save_f);
    Y(free)
    (got);
  }
  Y(free)
  (N);
  Y(free)
  (n);
  Y(free)
  (x);
  Y(free)
  (f_hat);
  Y(free)
  (f);
}

/* The same reference cases through the composed fast solver, forced with
 * NFFT_NO_DIRECT. guards_ok declines N <= m, n <= 2m + 2 and sigma <= 1; with
 * m = 6 and n = 2N that leaves every axis with N > 6. Returns 1 if the case
 * ran, 0 if the guard skipped it, so the caller can fail loudly on a guard
 * regression that drops every case. */
static int run_native_fast(const native_testcase_t *tc)
{
  const int m = 6;
  int d, t, ok = 1;
  INT *N, NN, M, *n;
  R *x;
  C *f_hat, *f;
  Y(plan_ng) * p;
  R tol = (R)1.0e-6;
  if ((R)1.0e4 * EPSILON > tol)
    tol = (R)1.0e4 * EPSILON;
  if (!read_case(tc->filename, &d, &N, &NN, &M, &x, &f_hat, &f)) {
    CU_FAIL("read_case failed");
    Y(free)
    (N);
    Y(free)
    (x);
    Y(free)
    (f_hat);
    Y(free)
    (f);
    return 0;
  }
  n = (INT *)Y(malloc)((size_t)d * sizeof(INT));
  for (t = 0; t < d; t++) {
    n[t] = 2 * N[t];
    if (!(N[t] > (INT)m) || !(n[t] > (INT)(2 * m + 2)) || !(n[t] > N[t]))
      ok = 0;
  }
  if (ok) {
    if (tc->kind == 0) /* trafo: input f_hat, expected f */
    {
      C *save_fhat = (C *)Y(malloc)((size_t)NN * sizeof(C));
      C *got = (C *)Y(malloc)((size_t)M * sizeof(C));
      INT j;
      for (j = 0; j < NN; j++)
        save_fhat[j] = f_hat[j];
      p = Y(plan_ng_guru)(d, N, tc->variant, n, M, m,
                          NFFT_WINDOW_KAISER_BESSEL, x, f_hat, got, 0u,
                          NFFT_ESTIMATE | NFFT_NO_DIRECT);
      CU_ASSERT_PTR_NOT_NULL_FATAL(p);
      Y(precompute)
      (p);
      for (j = 0; j < NN; j++)
        f_hat[j] = save_fhat[j];
      Y(execute)
      (p);
      CU_ASSERT(rel_max_errC(got, f, M) < tol);
      Y(plan_ng_destroy)
      (p);
      Y(free)
      (save_fhat);
      Y(free)
      (got);
    } else /* adjoint: input f, expected f_hat */
    {
      C *save_f = (C *)Y(malloc)((size_t)M * sizeof(C));
      C *got = (C *)Y(malloc)((size_t)NN * sizeof(C));
      INT j;
      for (j = 0; j < M; j++)
        save_f[j] = f[j];
      p = Y(plan_ng_guru)(d, N, tc->variant, n, M, m,
                          NFFT_WINDOW_KAISER_BESSEL, x, got, f, 0u,
                          NFFT_ESTIMATE | NFFT_NO_DIRECT);
      CU_ASSERT_PTR_NOT_NULL_FATAL(p);
      Y(precompute)
      (p);
      for (j = 0; j < M; j++)
        f[j] = save_f[j];
      Y(execute_adjoint)
      (p);
      CU_ASSERT(rel_max_errC(got, f_hat, NN) < tol);
      Y(plan_ng_destroy)
      (p);
      Y(free)
      (save_f);
      Y(free)
      (got);
    }
  }
  Y(free)
  (N);
  Y(free)
  (n);
  Y(free)
  (x);
  Y(free)
  (f_hat);
  Y(free)
  (f);
  return ok;
}

void Y(check_nplan_data)(void) {
  int i, ran_fast = 0;
  for (i = 0; i < native_testcases_count; i++) {
    const native_testcase_t *tc = &native_testcases[i];
    run_native(tc, 0u);
    ran_fast += run_native_fast(tc); /* the composed fast, where the guard admits it */
  }
  /* A guard regression that rejects every case would leave this suite
   * silently short of fast-path coverage; the reference grid clears the
   * guard on 62 cases (measured: 31 trafo + 31 adjoint). The floor of 20
   * is a deliberate margin below that, not a near-binding bound. */
  CU_ASSERT(ran_fast >= 20);
  /* Reset the process-global planner so later suites see a fresh generation. */
  Y(the_planner_destroy)
  ();
}
