#include<stdlib.h>
#include<stdio.h>
#include<complex.h>

#include<texture_util.h>

// fixed parameters
int seed = 0;
const char *omega_prefix = "omega/";

// input parameters
int N, testcases;
// 4: 1/(l+1)^1.5 (circle)
int omega_policy = 4;
char omega_file_name[100];

// program variables
complex *omega;

void input() {
	// N
	printf("N: ");
	scanf("%d", &N);
	
	// testcases
	printf("testcases: ");
	scanf("%d", &testcases);
	
	// omega_policy
	printf("omega_policy (4: %s), (5: %s): ", omega_policy_descr[4], omega_policy_descr[5]);
	scanf("%d", &omega_policy);
	
	// omega_file_name
	printf("omega_file_name: ");
	scanf("%s", omega_file_name);
}

void init() {
	srand(seed);
	omega = smart_malloc(texture_flat_length(N) * sizeof(complex));
}

void process() {
	int count;

	for (count = 0; count < testcases; count++) {
		char omega_path[200];
		FILE *omega_file;

		sprintf(omega_path, "%s%s%03d", omega_prefix, omega_file_name, count);
		omega_file = fopen(omega_path, "w");

		init_omega(omega, N, omega_policy);

		fprintf(omega_file, "Omega\n");
		fprintf(omega_file, "# Generated by paper1/reconstruction/create_omega.\n");
		fprintf(omega_file, "# omega_policy: %d (%s)\n", omega_policy, omega_policy_descr[omega_policy]);
		write_omega(N, omega, omega_file);

		fclose(omega_file);
	}
}

void clean_up() {
	free(omega);
}

int main() {

	input();

	init();
	
	process();

	clean_up();
	
	return 0;
}
