m=0:14;
load kaiser_bessel.dat
load sinc_power.dat
load b_spline.dat
load gaussian.dat

figure(1);
h=semilogy(m,kaiser_bessel(m+1,1),'k',m,kaiser_bessel(m+1,1),'ko',...
           m,sinc_power(m+1,1),'k',m,sinc_power(m+1,1),'kx',...
           m,b_spline(m+1,1),'k',m,b_spline(m+1,1),'k+',...
           m,gaussian(m+1,1),'k',m,gaussian(m+1,1),'k^');
set(h,'LineWidth',2.0); set(h,'Markersize',10); set(gca,'FontSize',22); print accuracy1.eps -deps

figure(2);
h=semilogy(m,kaiser_bessel(m+1,2),'k',m,kaiser_bessel(m+1,2),'ko',...
           m,sinc_power(m+1,2),'k',m,sinc_power(m+1,2),'kx',...
           m,b_spline(m+1,2),'k',m,b_spline(m+1,2),'k+',...
           m,gaussian(m+1,2),'k',m,gaussian(m+1,2),'k^');
set(h,'LineWidth',2.0); set(h,'Markersize',10); set(gca,'FontSize',22); print accuracy2.eps -deps

figure(3);
h=semilogy(m,kaiser_bessel(m+16,1),'k',m,kaiser_bessel(m+16,1),'ko',...
           m,sinc_power(m+16,1),'k',m,sinc_power(m+16,1),'kx',...
           m,b_spline(m+16,1),'k',m,b_spline(m+16,1),'k+',...
           m,gaussian(m+16,1),'k',m,gaussian(m+16,1),'k^');
set(h,'LineWidth',2.0); set(h,'Markersize',10); set(gca,'FontSize',22); print accuracy3.eps -deps

figure(4);
h=semilogy(m,kaiser_bessel(m+16,2),'k',m,kaiser_bessel(m+16,2),'ko',...
           m,sinc_power(m+16,2),'k',m,sinc_power(m+16,2),'kx',...
           m,b_spline(m+16,2),'k',m,b_spline(m+16,2),'k+',...
           m,gaussian(m+16,2),'k',m,gaussian(m+16,2),'k^');
set(h,'LineWidth',2.0); set(h,'Markersize',10); set(gca,'FontSize',22); print accuracy4.eps -deps

figure(5);
h=semilogy(m,kaiser_bessel(m+31,1),'k',m,kaiser_bessel(m+31,1),'ko',...
           m,sinc_power(m+31,1),'k',m,sinc_power(m+31,1),'kx',...
           m,b_spline(m+31,1),'k',m,b_spline(m+31,1),'k+',...
           m,gaussian(m+31,1),'k',m,gaussian(m+31,1),'k^');
set(h,'LineWidth',2.0); set(h,'Markersize',10); set(gca,'FontSize',22); print accuracy5.eps -deps

figure(6);
h=semilogy(m,kaiser_bessel(m+31,2),'k',m,kaiser_bessel(m+31,2),'ko',...
           m,sinc_power(m+31,2),'k',m,sinc_power(m+31,2),'kx',...
           m,b_spline(m+31,2),'k',m,b_spline(m+31,2),'k+',...
           m,gaussian(m+31,2),'k',m,gaussian(m+31,2),'k^');
set(h,'LineWidth',2.0); set(h,'Markersize',10); set(gca,'FontSize',22); print accuracy6.eps -deps
