"""Emit kernel/util/bessel_i0_data.h.

Replaces the Mathematica notebook that used to produce the I0 coefficient
tables. Everything here is deterministic: same spec in, same bytes out.

    uv run --with mpmath==1.3.0 python -m tests.besselgen.generate

`--search` re-derives the degrees from the accuracy target instead of using
the pinned ones, and prints them so SPEC can be updated deliberately.
"""
import argparse
import sys

import mpmath as mp

from . import scheme

# Per-format scheme: split, degree of P1, degree of P2.
#
# Two constraints fix these, beyond reaching the accuracy target.
#
# The split is set by branch 2's conditioning. P2 ships as monomial
# coefficients in u = 1/x so the runtime can sum it as independent chains, and
# that form is well conditioned only while the degree stays low. Past roughly
# degree 24 the growth factor leaves 1 and climbs fast: at MANT_DIG 64 a split
# of 10 needs degree 32 and gives 466, and at MANT_DIG 113 a split of 15 needs
# degree 59 and gives 1.2e9. Raising the split shortens branch 2 until the
# factor returns to 1, and branch 1 absorbs the degree at no risk, its
# coefficients being positive however long it gets. scheme.branch2_growth
# measures it and the generator reports it.
#
# Both degrees are then rounded up so that the table length n+1 is a multiple
# of four, which is what lets the four-chain loop in bessel_i0.c run without a
# prologue. Rounding up only lowers the design error.
#
# --search re-derives the degrees; the splits are deliberate, not searched.
SPEC = {
    24: dict(split=8, n1=11, n2=7),
    53: dict(split=10, n1=19, n2=23),
    64: dict(split=15, n1=23, n2=23),
    113: dict(split=25, n1=43, n2=39),
}

# Working precision and printed digits per format. The printed digit count is
# comfortably above the round-trip minimum (9/17/21/36).
DIGITS = {24: 12, 53: 20, 64: 25, 113: 40}
GUARD = {24: "MANT_DIG == 24", 53: "MANT_DIG == 53",
         64: "MANT_DIG == 64", 113: "MANT_DIG == 113"}
NAME = {24: "IEEE 754 single precision, 32 bits.",
        53: "IEEE 754 double precision, 64 bits.",
        64: "Intel double extended, 80 bits.",
        113: "IEEE 754 quadruple precision, 128 bits."}

HEADER = """/*
 * Copyright (c) 2002, 2017 Jens Keiner, Stefan Kunis, Daniel Potts
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/* Generated by tests/besselgen -- do not edit.
 *
 * Coefficients for the modified Bessel function I0, one set per floating-point
 * format. Regenerate with
 *
 *   uv run --with mpmath==1.3.0 python -m tests.besselgen.generate
 *
 * Two ranges per format, split at NFFT_I0_ASYMP_SPLIT:
 *
 *   x <= split   I0(x) = 1 + y * P1(y),  y = (x/2)^2.
 *                Every P1 coefficient is positive, so the sum cannot cancel,
 *                and the leading 1 makes the form exact at x = 0.
 *
 *   x >  split   I0(x) = exp(x)/sqrt(x) * P2(u),  u = 1/x in (0, 1/split],
 *                monomial in u, fitted against the exponentially scaled
 *                sqrt(x)*exp(-x)*I0(x). The split is chosen per format so that
 *                this form cannot cancel, which caps its degree.
 *
 * Both are weighted minimax fits, so the weighted error equioscillates and the
 * design error of each is far below the format epsilon; what is left at run
 * time is rounding in the evaluation itself.
 *
 * Each table length is a multiple of four: bessel_i0.c sums both as four
 * independent chains, and that lets the loop run without a prologue.
 */

#ifndef NFFT_BESSEL_I0_DATA_H
#define NFFT_BESSEL_I0_DATA_H
"""

FOOTER = """
#endif /* NFFT_BESSEL_I0_DATA_H */
"""


def cnum(v, digits):
    """An mpf as a C literal inside K(...), always in exponential form."""
    s = mp.nstr(v, digits, min_fixed=0, max_fixed=0, strip_zeros=False)
    if "e" not in s and "E" not in s:
        s = s + "e0"
    return s


def emit_array(name, coeffs, digits, out):
    out.append("  static const R %s[] =" % name)
    out.append("  {")
    for v in coeffs:
        out.append("      K(%s)," % cnum(v, digits))
    out.append("  };")


def build(prec, spec, dps, search_target=None, log=None):
    mp.mp.dps = dps
    split = spec["split"]
    if search_target is not None:
        n1 = _search(scheme.fit_branch1, split, search_target)
        n2 = _search(scheme.fit_branch2, split, search_target)
        if log:
            log("  searched degrees: n1=%d n2=%d" % (n1, n2))
    else:
        n1, n2 = spec["n1"], spec["n2"]
    P1, e1 = scheme.fit_branch1(split, n1)
    P2, e2 = scheme.fit_branch2(split, n2)
    g2 = scheme.branch2_growth(P2, split)
    return dict(split=split, n1=n1, n2=n2, P1=P1, P2=P2, e1=e1, e2=e2, g2=g2)


def _search(fit, split, target, lo=3, hi=60):
    for n in range(lo, hi + 1):
        _, err = fit(split, n)
        if err <= target:
            return n
    raise RuntimeError("no degree <= %d reaches %s" % (hi, target))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="kernel/util/bessel_i0_data.h")
    ap.add_argument("--precisions", default="24,53,64,113")
    ap.add_argument("--dps", type=int, default=0,
                    help="mpmath working digits (default: per-format)")
    ap.add_argument("--search", action="store_true",
                    help="re-derive degrees from the accuracy target")
    ap.add_argument("--split", type=float, default=None,
                    help="override the split (single precision only)")
    ap.add_argument("--n1", type=int, default=None,
                    help="override the branch-1 degree (single precision only)")
    ap.add_argument("--n2", type=int, default=None,
                    help="override the branch-2 degree (single precision only)")
    args = ap.parse_args(argv)

    precs = [int(p) for p in args.precisions.split(",")]
    if (args.split or args.n1 or args.n2) and len(precs) != 1:
        ap.error("--split/--n1/--n2 apply to a single precision")
    # Double goes last, as the #else, so a format this file does not know about
    # still compiles against the double set rather than failing the build --
    # what the hand-written table did, and what long double on a double-double
    # platform (MANT_DIG 106) relies on.
    tail = 53 if 53 in precs else None
    ordered = [p for p in precs if p != tail]
    out = [HEADER]
    first = True
    for prec in ordered:
        dps = args.dps or (60 if prec <= 64 else 90)
        target = mp.mpf(2) ** (-prec - 8)
        sys.stderr.write("fitting MANT_DIG=%d (dps=%d)\n" % (prec, dps))
        spec = dict(SPEC[prec])
        for key, val in (("split", args.split), ("n1", args.n1), ("n2", args.n2)):
            if val is not None:
                spec[key] = val
        r = build(prec, spec, dps,
                  search_target=target if args.search else None,
                  log=lambda s: sys.stderr.write(s + "\n"))
        sys.stderr.write("  split=%s n1=%d n2=%d design err %s / %s"
                         "  P2 growth %s\n"
                         % (r["split"], r["n1"], r["n2"],
                            mp.nstr(r["e1"], 3), mp.nstr(r["e2"], 3),
                            mp.nstr(r["g2"], 6)))
        out.append("")
        out.append("#%s %s" % ("if" if first else "elif", GUARD[prec]))
        first = False
        out.append("  /* %s */" % NAME[prec])
        out.append("#  define NFFT_I0_ASYMP_SPLIT K(%s)" % _split_literal(r["split"]))
        emit_array("NFFT_I0_P1", r["P1"], DIGITS[prec], out)
        emit_array("NFFT_I0_P2", r["P2"], DIGITS[prec], out)

    out.append("")
    if tail is None:
        out.append("#else")
        out.append("#  error \"unsupported floating-point format: no I0 coefficients\"")
    else:
        dps = args.dps or 60
        sys.stderr.write("fitting MANT_DIG=%d (dps=%d, emitted as the fallback)\n"
                         % (tail, dps))
        r = build(tail, SPEC[tail], dps)
        sys.stderr.write("  split=%s n1=%d n2=%d design err %s / %s"
                         "  P2 growth %s\n"
                         % (r["split"], r["n1"], r["n2"],
                            mp.nstr(r["e1"], 3), mp.nstr(r["e2"], 3),
                            mp.nstr(r["g2"], 6)))
        out.append("#else")
        out.append("  /* %s Also the fallback for any format not named above." % NAME[tail])
        out.append("   * Correct there only if that format is no wider than double. */")
        out.append("#  define NFFT_I0_ASYMP_SPLIT K(%s)" % _split_literal(r["split"]))
        emit_array("NFFT_I0_P1", r["P1"], DIGITS[tail], out)
        emit_array("NFFT_I0_P2", r["P2"], DIGITS[tail], out)
    out.append("#endif")
    out.append(FOOTER)

    text = "\n".join(out) + "\n"
    text = text.replace("\n\n\n", "\n\n")
    with open(args.out, "w") as fh:
        fh.write(text)
    sys.stderr.write("wrote %s\n" % args.out)
    return 0


def _split_literal(s):
    return "%.1f" % float(s)


if __name__ == "__main__":
    raise SystemExit(main())
