"""Generate the committed C registration header and the data Makefile.am list.

The header replaces the hand-maintained testcase_delegate_file_t declarations and
testcases_*_file[] arrays inside tests/<module>.c. The .c #includes it."""

from tests.refgen import grids as G

_MODULES = ("nfft", "nfct", "nfst")


def _legacy_grid(module):
    # The legacy (tests/nfft.c) roster only ever knew the original nfft grid
    # (type-I, some even some odd N — e.g. N=1). New odd-N/type-II additions
    # are native-only and must not perturb the legacy
    # header or tests/nfft.c's registration arrays, so filter by exact
    # membership in G.NFFT_LEGACY_GRID rather than re-deriving "legacy" from
    # a parity/variant heuristic.
    if module != "nfft":
        return [(d, N, M) for (d, N, M, _variant) in G.GRIDS[module]]
    return [(d, N, M) for (d, N, M, _variant) in G.NFFT_LEGACY_GRID]


def _decl(module, kind, d, N, M):
    base = G.basename(module, kind, d, N, M)
    return ('static const testcase_delegate_file_t %s = '
            '{setup_file, destroy_file, ABSPATH("data/%s.txt")};' % (base, base))


def _array(module, kind, d, grid):
    # Match the existing C symbols exactly: "adjoint" precedes the dimension.
    # Forward:  testcases_<d>d_file[]          (alias testcases_<d>d_file_)
    # Adjoint:  testcases_adjoint_<d>d_file[]  (alias testcases_adjoint_<d>d_file_)
    prefix = "adjoint_" if kind == "adjoint" else ""
    arr = "testcases_%s%dd_file" % (prefix, d)
    entries = [G.basename(module, kind, d, N, M)
               for (dd, N, M) in grid if dd == d]
    lines = ["static const testcase_delegate_file_t *%s[] =" % arr, "{"]
    lines += ["  &%s," % e for e in entries]
    lines += ["};",
              "static const testcase_delegate_t **%s_ = "
              "(const testcase_delegate_t**)%s;" % (arr, arr)]
    return "\n".join(lines)


def render_header(module):
    grid = _legacy_grid(module)
    guard = "NFFT3_TESTS_DATA_GENERATED_%s_TESTCASES_H" % module.upper()
    dims = sorted({d for (d, _N, _M) in grid})
    out = [
        "/* GENERATED by tests/refgen — do not edit by hand.",
        " * Regenerate: python -m tests.refgen.generate --module %s" % module,
        " */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
    ]
    for kind in G.KINDS:
        for d in dims:
            for (dd, N, M) in grid:
                if dd == d:
                    out.append(_decl(module, kind, d, N, M))
            out.append("")
            out.append(_array(module, kind, d, grid))
            out.append("")
    out.append("#endif /* %s */" % guard)
    return "\n".join(out) + "\n"


def render_extra_dist():
    # Every generated data file, not just the legacy roster: the native-only
    # cases are consumed by the planner-API suites and must ship too.
    files = []
    for module in _MODULES:
        for kind in G.KINDS:
            for (d, N, M, variant) in G.GRIDS[module]:
                files.append(G.basename(module, kind, d, N, M, variant) + ".txt")
    files = sorted(set(files))
    body = "  \\\n".join(files)
    return "EXTRA_DIST = " + body + "\n"


def _native_cases():
    """Every nfft (d, N, M, variant) case, both kinds, in GRIDS order."""
    cases = []
    for kind in G.KINDS:
        for (d, N, M, variant) in G.GRIDS["nfft"]:
            cases.append((kind, d, N, M, variant))
    return cases


def _c_ident(base):
    return base.replace("-", "_")


def render_native_header():
    """Render tests/data/generated/nfft_native_testcases.h: a flat roster of every
    nfft case (both kinds), consumed by the native-planner test suite.
    Unlike render_header, this includes odd-N and type-II cases too."""
    guard = "NFFT3_TESTS_DATA_GENERATED_NFFT_NATIVE_TESTCASES_H"
    out = [
        "/* GENERATED by tests/refgen — do not edit by hand.",
        " * Regenerate: python -m tests.refgen.generate --module nfft",
        " */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "typedef struct { const char *filename; int d; const int *variant; int kind; } native_testcase_t;",
        "/* kind: 0 = trafo, 1 = adjoint */",
        "",
    ]

    cases = _native_cases()

    # Emit one `static const int native_variant_<basename>[]` array per type-II case.
    for (kind, d, N, M, variant) in cases:
        if variant is None:
            continue
        base = G.basename("nfft", kind, d, N, M, variant)
        vals = ", ".join(str(v) for v in variant)
        out.append("static const int native_variant_%s[] = { %s };" % (_c_ident(base), vals))
    out.append("")

    out.append("static const native_testcase_t native_testcases[] =")
    out.append("{")
    kind_tag = {"trafo": 0, "adjoint": 1}
    for (kind, d, N, M, variant) in cases:
        base = G.basename("nfft", kind, d, N, M, variant)
        variant_expr = ("native_variant_%s" % _c_ident(base)) if variant is not None else "0"
        out.append('  {"data/%s.txt", %d, %s, %d /*%s*/},'
                   % (base, d, variant_expr, kind_tag[kind], kind))
    out.append("};")
    out.append("static const int native_testcases_count = %d;" % len(cases))
    out.append("")
    out.append("#endif /* %s */" % guard)
    return "\n".join(out) + "\n"
