"""Generate the committed C registration header and the data Makefile.am list.

The header replaces the hand-maintained testcase_delegate_file_t declarations and
testcases_*_file[] arrays inside tests/<module>.c. The .c #includes it. This is the
mechanism that eliminates the manual-paste drift that left check_nfsft.nb stale."""

from tests.refgen import grids as G

_MODULES = ("nfft", "nfct", "nfst")


def _decl(module, kind, d, N, M):
    base = G.basename(module, kind, d, N, M)
    return ('static const testcase_delegate_file_t %s = '
            '{setup_file, destroy_file, ABSPATH("data/%s.txt")};' % (base, base))


def _array(module, kind, d):
    # Match the existing C symbols exactly: "adjoint" precedes the dimension.
    # Forward:  testcases_<d>d_file[]          (alias testcases_<d>d_file_)
    # Adjoint:  testcases_adjoint_<d>d_file[]  (alias testcases_adjoint_<d>d_file_)
    prefix = "adjoint_" if kind == "adjoint" else ""
    arr = "testcases_%s%dd_file" % (prefix, d)
    entries = [G.basename(module, kind, d, N, M)
               for (dd, N, M) in G.GRIDS[module] if dd == d]
    lines = ["static const testcase_delegate_file_t *%s[] =" % arr, "{"]
    lines += ["  &%s," % e for e in entries]
    lines += ["};",
              "static const testcase_delegate_t **%s_ = "
              "(const testcase_delegate_t**)%s;" % (arr, arr)]
    return "\n".join(lines)


def render_header(module):
    guard = "NFFT3_TESTS_DATA_GENERATED_%s_TESTCASES_H" % module.upper()
    dims = sorted({d for (d, _N, _M) in G.GRIDS[module]})
    out = [
        "/* GENERATED by tests/refgen — do not edit by hand.",
        " * Regenerate: python -m tests.refgen.generate --module %s" % module,
        " */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
    ]
    for kind in G.KINDS:
        for d in dims:
            for (dd, N, M) in G.GRIDS[module]:
                if dd == d:
                    out.append(_decl(module, kind, d, N, M))
            out.append("")
            out.append(_array(module, kind, d))
            out.append("")
    out.append("#endif /* %s */" % guard)
    return "\n".join(out) + "\n"


def render_extra_dist():
    files = []
    for module in _MODULES:
        for kind in G.KINDS:
            for (d, N, M) in G.GRIDS[module]:
                files.append(G.basename(module, kind, d, N, M) + ".txt")
    files = sorted(set(files))
    body = "  \\\n".join(files)
    return "EXTRA_DIST = " + body + "\n"
