#!/usr/bin/env bash
# Checks that the CMake-generated and Autotools config.h stay in lockstep while
# both build systems coexist, in BOTH directions:
#
#   forward  — every macro the Autotools-GENERATED config.h defines must also be
#              defined by the CMake config.h. Catches the CMake port silently
#              dropping a feature macro the shared source relies on.
#   reverse  — every macro the CMake config.h defines must be KNOWN to Autotools,
#              i.e. present in its config.h.in TEMPLATE. Catches a macro added to
#              cmake.config.h.in that the shared source starts using but Autotools'
#              config system was never taught to emit.
#
# The reverse direction compares against the Autotools TEMPLATE, not its generated
# config.h, on purpose: Autotools runs AC_CHECK_DECLS only for the configured
# precision, so its generated config.h carries just one precision's HAVE_DECL_*
# while CMake emits all three. Those extra HAVE_DECL_* all exist in the template
# (merely inactive for this build), so comparing against the template removes that
# benign precision-conditional noise without losing real coverage.
#
# Run from the repo root with both build trees present.
set -euo pipefail

AUTOTOOLS_CONFIG="${1:-include/config.h}"        # generated by ./configure
CMAKE_CONFIG="${2:-build/config.h}"              # generated by cmake -S . -B build
AUTOTOOLS_TEMPLATE="${3:-include/config.h.in}"   # autoheader template (all precisions)

# Macros deliberately exempt from parity:
#   NFFT_CONFIG_H — the CMake config.h include guard, not a feature macro.
#   HAVE_OPENMP   — emitted only by Autotools (an AX_OPENMP side effect keyed on
#                   compiler capability, not on --enable-openmp) and consumed by no
#                   source (the code uses the standard _OPENMP). Intentionally
#                   absent from the CMake config; will vanish with Autotools.
EXCLUDE='^(NFFT_CONFIG_H|HAVE_OPENMP)$'

syms() { grep -oE '^#(define|undef) [A-Za-z0-9_]+' "$1" | awk '{print $2}' | grep -vE "$EXCLUDE" | sort -u; }

status=0

missing_from_cmake="$(comm -23 <(syms "$AUTOTOOLS_CONFIG") <(syms "$CMAKE_CONFIG") || true)"
if [ -n "$missing_from_cmake" ]; then
  echo "ERROR: CMake config.h is missing symbols defined by the Autotools config.h:" >&2
  echo "$missing_from_cmake" >&2
  status=1
fi

unknown_to_autotools="$(comm -23 <(syms "$CMAKE_CONFIG") <(syms "$AUTOTOOLS_TEMPLATE") || true)"
if [ -n "$unknown_to_autotools" ]; then
  echo "ERROR: CMake config.h defines symbols unknown to the Autotools config.h.in template:" >&2
  echo "$unknown_to_autotools" >&2
  status=1
fi

if [ "$status" -ne 0 ]; then
  exit 1
fi
echo "config parity OK: CMake defines every Autotools symbol and nothing the Autotools template lacks."
