# In-tree config.h guard.
#
# The Autotools configure writes a generated config.h into the *source* tree,
# at include/config.h. include/infft.h includes "config.h" with quotes, and a
# quoted include searches the directory of the including file before any -I
# path, so that file then wins over the config.h this build generates. The
# build stays silent and takes the Autotools tree's precision: a float tree
# produces a library that exports nfft_* and no nfftf_*.
#
# Distinct from cmake/config-parity-check.sh, which compares the macro sets of
# the two build systems' headers. This one is about one header shadowing the
# other at compile time.
#
# Usable two ways:
#   include(nfft_intree_config_h)                      at configure time
#   cmake -DNFFT_SOURCE_DIR=<dir> -P <this file>       at build time
#
# NFFT_ALLOW_INTREE_CONFIG_H=ON turns it off.

if(NOT DEFINED NFFT_SOURCE_DIR)
  set(NFFT_SOURCE_DIR "${PROJECT_SOURCE_DIR}")
endif()

if(NOT NFFT_ALLOW_INTREE_CONFIG_H AND EXISTS "${NFFT_SOURCE_DIR}/include/config.h")
  message(FATAL_ERROR
    "${NFFT_SOURCE_DIR}/include/config.h exists. It is generated by the "
    "Autotools configure and, because include/infft.h includes \"config.h\" "
    "with quotes, it overrides this build's own config.h and silently changes "
    "its precision. Run 'make distclean' in the source tree (or delete the "
    "file) and build again. Set NFFT_ALLOW_INTREE_CONFIG_H=ON to override.")
endif()
