(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



AppendTo[$Path, NotebookDirectory[]];
<<PrintVector`


P=64;(* Working precision. *)


BSpline[n_][x_]:=BSplineBasis[n,x/(n+1)];
Generate[n_]:=Module[
{
m=100
},
x=Sort[RandomReal[{0,(n+1)/2},m,WorkingPrecision->P]];
y=Map[BSpline[n],x];
FormatVector[Flatten[N[Transpose[{x,y}],P]], "b" <> ToString[n]]];



