"""Emit kernel/util/sinc_data.h.

    uv run --with mpmath==1.3.0 python -m tests.sincgen.generate

`--search` re-derives the degrees from the accuracy target instead of using the
pinned ones, and prints them so SPEC can be updated deliberately.
"""
import argparse
import sys

import mpmath as mp

from . import scheme

# Per-format scheme: the split and the degree of Q.
#
# The split is 2 for every format, and is not a free knob: it is the largest
# round value at which the monomial Horner chain still cannot cancel (growth
# factor 1.000; at 2.5 it is already 53). It also puts the whole B-spline
# PHI_HUT range, |t| <= pi/2, inside the polynomial branch.
SPEC = {
    24: dict(split=2, n=9),
    53: dict(split=2, n=19),
    64: dict(split=2, n=22),
    113: dict(split=2, n=39),
}

DIGITS = {24: 12, 53: 20, 64: 25, 113: 40}
GUARD = {24: "MANT_DIG == 24", 53: "MANT_DIG == 53",
         64: "MANT_DIG == 64", 113: "MANT_DIG == 113"}
NAME = {24: "IEEE 754 single precision, 32 bits.",
        53: "IEEE 754 double precision, 64 bits.",
        64: "Intel double extended, 80 bits.",
        113: "IEEE 754 quadruple precision, 128 bits."}

HEADER = """/*
 * Copyright (c) 2002, 2017 Jens Keiner, Stefan Kunis, Daniel Potts
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/* Generated by tests/sincgen -- do not edit.
 *
 * Coefficients for log|sinc(x)|, one set per floating-point format.
 * Regenerate with
 *
 *   uv run --with mpmath==1.3.0 python -m tests.sincgen.generate
 *
 * Two ranges per format, split at NFFT_LOG_SINC_SPLIT:
 *
 *   |x| <= split   log|sinc(x)| = y * Q(y),  y = x*x, Horner in y.
 *                  The leading y makes the form exact at x = 0, and the
 *                  coefficients follow the Taylor series of log sinc
 *                  (-1/6, -1/180, -1/2835, ...), all negative, so the sum
 *                  cannot cancel.
 *
 *   |x| >  split   log|sinc(x)| = LOG(FABS(SIN(x)/x)), no coefficients.
 *
 * Q is a weighted minimax fit, the weight chosen so the relative error of
 * y*Q(y) equioscillates. What callers need is the absolute error of the
 * result, since they form EXP(2m * log_sinc(x)); branch 1 gives |L|*eps where
 * the direct logarithm could only give eps.
 */

#ifndef NFFT_SINC_DATA_H
#define NFFT_SINC_DATA_H
"""

FOOTER = """
#endif /* NFFT_SINC_DATA_H */
"""


def cnum(v, digits):
    """An mpf as a C literal inside K(...), always in exponential form."""
    s = mp.nstr(v, digits, min_fixed=0, max_fixed=0, strip_zeros=False)
    if "e" not in s and "E" not in s:
        s = s + "e0"
    return s


def emit_array(name, coeffs, digits, out):
    out.append("  static const R %s[] =" % name)
    out.append("  {")
    for v in coeffs:
        out.append("      K(%s)," % cnum(v, digits))
    out.append("  };")


def build(spec, dps, search_target=None, log=None):
    mp.mp.dps = dps
    split = spec["split"]
    if search_target is not None:
        n = _search(split, search_target)
        if log:
            log("  searched degree: n=%d" % n)
    else:
        n = spec["n"]
    Q, err = scheme.fit_branch(split, n)
    growth = scheme.horner_growth(Q, split)
    return dict(split=split, n=n, Q=Q, err=err, growth=growth)


def _search(split, target, lo=3, hi=80):
    for n in range(lo, hi + 1):
        _, err = scheme.fit_branch(split, n)
        if err <= target:
            return n
    raise RuntimeError("no degree <= %d reaches %s" % (hi, target))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="kernel/util/sinc_data.h")
    ap.add_argument("--precisions", default="24,53,64,113")
    ap.add_argument("--dps", type=int, default=0,
                    help="mpmath working digits (default: per-format)")
    ap.add_argument("--search", action="store_true",
                    help="re-derive degrees from the accuracy target")
    ap.add_argument("--split", type=float, default=None,
                    help="override the split (single precision only)")
    ap.add_argument("--n", type=int, default=None,
                    help="override the degree (single precision only)")
    args = ap.parse_args(argv)

    precs = [int(p) for p in args.precisions.split(",")]
    if (args.split or args.n) and len(precs) != 1:
        ap.error("--split/--n apply to a single precision")
    # Double goes last, as the #else, so a format this file does not know about
    # still compiles against the double set rather than failing the build.
    tail = 53 if 53 in precs else None
    ordered = [p for p in precs if p != tail]
    out = [HEADER]
    first = True

    def report(prec, r):
        sys.stderr.write("  split=%s n=%d design err %s  Horner growth %s\n"
                         % (r["split"], r["n"], mp.nstr(r["err"], 3),
                            mp.nstr(r["growth"], 6)))

    for prec in ordered:
        dps = args.dps or (60 if prec <= 64 else 90)
        target = mp.mpf(2) ** (-prec - 8)
        sys.stderr.write("fitting MANT_DIG=%d (dps=%d)\n" % (prec, dps))
        spec = dict(SPEC[prec])
        for key, val in (("split", args.split), ("n", args.n)):
            if val is not None:
                spec[key] = val
        r = build(spec, dps, search_target=target if args.search else None,
                  log=lambda s: sys.stderr.write(s + "\n"))
        report(prec, r)
        out.append("")
        out.append("#%s %s" % ("if" if first else "elif", GUARD[prec]))
        first = False
        out.append("  /* %s */" % NAME[prec])
        out.append("#  define NFFT_LOG_SINC_SPLIT K(%s)" % _split_literal(r["split"]))
        emit_array("NFFT_LOG_SINC_Q", r["Q"], DIGITS[prec], out)

    out.append("")
    if tail is None:
        out.append("#else")
        out.append("#  error \"unsupported floating-point format: no log sinc coefficients\"")
    else:
        dps = args.dps or 60
        sys.stderr.write("fitting MANT_DIG=%d (dps=%d, emitted as the fallback)\n"
                         % (tail, dps))
        r = build(SPEC[tail], dps)
        report(tail, r)
        out.append("#else")
        out.append("  /* %s Also the fallback for any format not named above." % NAME[tail])
        out.append("   * Correct there only if that format is no wider than double. */")
        out.append("#  define NFFT_LOG_SINC_SPLIT K(%s)" % _split_literal(r["split"]))
        emit_array("NFFT_LOG_SINC_Q", r["Q"], DIGITS[tail], out)
    out.append("#endif")
    out.append(FOOTER)

    text = "\n".join(out) + "\n"
    text = text.replace("\n\n\n", "\n\n")
    with open(args.out, "w") as fh:
        fh.write(text)
    sys.stderr.write("wrote %s\n" % args.out)
    return 0


def _split_literal(s):
    return "%.1f" % float(s)


if __name__ == "__main__":
    raise SystemExit(main())
